services:
  texlyre-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_STORAGE_MODE: ${VITE_STORAGE_MODE:-hybrid}
        VITE_WS_URL: ${VITE_WS_URL:-ws://localhost:1234}
    container_name: texlyre-frontend
    hostname: texlyre-frontend
    restart: always
    ports:
      - "7080:80"
    networks:
      - tex-network

networks:
  tex-network:
    external: true

